import Link from "next/link";
import { redirect } from "next/navigation";
import { AppShell } from "@/app/_components/app-shell";
import { getAuthContext } from "@/lib/auth";
import { listGaaEligibleReports } from "@/lib/payment-recommendations";
import { prisma } from "@/lib/prisma";
import { CreateRecommendation } from "./create-recommendation";

export default async function GaaPaymentRecommendationsPage() { const { sessionUser, appUser } = await getAuthContext(); if (!sessionUser) redirect("/login"); if (!appUser || appUser.role !== "GAA") return <main className="p-8">Access denied.</main>; const reports = await listGaaEligibleReports(prisma, appUser); const totals = reports.reduce((sum, report) => sum + Number(report.paymentRecommendation?.overallRecommendedPayment ?? 0), 0); return <AppShell user={appUser}><div className="mx-auto flex w-full max-w-7xl flex-col gap-6"><header><p className="text-sm font-semibold uppercase tracking-[0.3em] text-cyan-700">GAA</p><h1 className="mt-2 text-3xl font-semibold text-slate-950">Payment Recommendations</h1><p className="mt-2 text-sm text-slate-600">Prepare task-level recommendations from Administration-approved reports.</p></header><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat label="Administration Approved" value={reports.length} /><Stat label="Draft Recommendations" value={reports.filter((r) => r.paymentRecommendation?.status === "DRAFT").length} /><Stat label="VC Pending" value={reports.filter((r) => r.paymentRecommendation?.status === "VC_PENDING").length} /><Stat label="Total Recommended" value={`LKR ${totals.toLocaleString("en-US", { minimumFractionDigits: 2 })}`} /></section><section className="overflow-x-auto rounded-3xl border border-slate-200 bg-white shadow-sm"><table className="min-w-full divide-y divide-slate-200"><thead className="bg-slate-50"><tr>{["Month", "Location", "Admin Status", "Recommendation", "Amount", "Action"].map((heading) => <th key={heading} className="px-5 py-3 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">{heading}</th>)}</tr></thead><tbody className="divide-y divide-slate-200">{reports.map((report) => <tr key={report.id}><td className="px-5 py-4 text-sm">{report.year}-{String(report.month).padStart(2, "0")}</td><td className="px-5 py-4 text-sm"><strong>{report.location.code}</strong> {report.location.name}</td><td className="px-5 py-4 text-sm">{report.status}</td><td className="px-5 py-4 text-sm">{report.paymentRecommendation?.status ?? "Not created"}</td><td className="px-5 py-4 text-sm">{report.paymentRecommendation ? `LKR ${Number(report.paymentRecommendation.overallRecommendedPayment).toLocaleString("en-US", { minimumFractionDigits: 2 })}` : "-"}</td><td className="px-5 py-4">{report.paymentRecommendation ? <Link className="font-semibold text-cyan-700" href={`/gaa/payment-recommendations/${report.paymentRecommendation.id}`}>Continue</Link> : <CreateRecommendation reportId={report.id} />}</td></tr>)}</tbody></table></section></div></AppShell>; }
function Stat({ label, value }: { label: string; value: number | string }) { return <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold text-slate-950">{value}</p></article>; }
