import Link from "next/link";
import { redirect } from "next/navigation";
import { AppShell } from "@/app/_components/app-shell";
import { getAuthContext } from "@/lib/auth";
import { getSystemStatistics, runSystemIntegrityChecks } from "@/lib/system-administration";
import { prisma } from "@/lib/prisma";
export default async function SystemAdministrationPage() { const { sessionUser, appUser } = await getAuthContext(); if (!sessionUser) redirect("/login"); if (!appUser || appUser.role !== "GAA") return <main className="p-8">Access denied.</main>; const [stats, health] = await Promise.all([getSystemStatistics(prisma), runSystemIntegrityChecks(prisma, appUser)]); return <AppShell user={appUser}><div className="mx-auto flex w-full max-w-7xl flex-col gap-6"><header><p className="text-sm font-semibold uppercase tracking-[0.3em] text-cyan-700">System Administration</p><h1 className="mt-2 text-3xl font-semibold">Quality Control Dashboard</h1><p className="mt-2 text-sm text-slate-600">Read-only monitoring of system activity, workflow status, and data integrity.</p></header><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><Stat label="Users" value={stats.users} /><Stat label="Active Locations" value={stats.activeLocations} /><Stat label="Active Tasks" value={stats.activeTasks} /><Stat label="Reports" value={stats.reports} /><Stat label="Finalized Recommendations" value={stats.statuses.finalized} /></section><section className={`rounded-3xl border p-6 ${health.status === "HEALTHY" ? "border-emerald-200 bg-emerald-50" : health.status === "CRITICAL" ? "border-red-200 bg-red-50" : "border-amber-200 bg-amber-50"}`}><h2 className="text-xl font-semibold">System Health: {health.status}</h2><p className="mt-2 text-sm">{health.criticalCount} critical issues · {health.warningCount} warnings</p><Link href="/system-administration/integrity" className="mt-4 inline-flex rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white">View Integrity Checks</Link></section><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><AdminLink href="/system-administration/audit" title="Audit Logs" detail="Search append-only system activity." /><AdminLink href="/system-administration/notifications" title="Notifications" detail="Review your notification center." /><AdminLink href="/system-administration/reports" title="Report History" detail="Browse finalized report history." /><AdminLink href="/system-administration/permissions" title="Permission Verification" detail="Review the current role access matrix." /></section></div></AppShell>; }
function Stat({ label, value }: { label: string; value: number }) { return <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></article>; }
function AdminLink({ href, title, detail }: { href: string; title: string; detail: string }) { return <Link href={href} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm hover:border-cyan-300"><p className="font-semibold">{title}</p><p className="mt-1 text-sm text-slate-600">{detail}</p></Link>; }
