ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'EVALUATING_OFFICER_ASSIGNED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'EVALUATING_OFFICER_ASSIGNMENT_ACTIVATED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'EVALUATING_OFFICER_ASSIGNMENT_DEACTIVATED';
