ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'PHI_ASSIGNED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'PHI_ASSIGNMENT_ACTIVATED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'PHI_ASSIGNMENT_DEACTIVATED';
