import Link from "next/link";
import { redirect } from "next/navigation";
import { AppShell } from "@/app/_components/app-shell";
import { getAuthContext } from "@/lib/auth";
import { getAdministrationDashboardData } from "@/lib/role-dashboards";
import { prisma } from "@/lib/prisma";

function formatDate(date: Date) { return new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric" }).format(date); }
function reportMonth(month: number, year: number) { return new Intl.DateTimeFormat("en", { month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(Date.UTC(year, month - 1, 1))); }
export default async function AdministrationDashboardPage() {
  const { sessionUser, appUser } = await getAuthContext();
  if (!sessionUser) redirect("/login");
  if (!appUser || appUser.role !== "ADMINISTRATION_OFFICER") return <AccessDenied />;
  let data;
  try { data = await getAdministrationDashboardData(prisma); } catch { return <AppShell user={appUser}><ErrorState /></AppShell>; }
  return <AppShell user={appUser}><div className="mx-auto flex w-full max-w-7xl flex-col gap-6"><header><p className="text-sm font-semibold uppercase tracking-[0.3em] text-cyan-700">Administration</p><h1 className="mt-2 text-3xl font-semibold text-slate-950">Administration Dashboard</h1><p className="mt-2 text-sm text-slate-600">Monthly Cleaning Report Review</p></header><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Stat title="Pending Review" value={data.pending} /><Stat title="SUBMITTED" value={data.submitted} /><Stat title="RESUBMITTED" value={data.resubmitted} /><Stat title="Approved" value={data.approved} /><Stat title="Rejected" value={data.rejected} /></section><Link href="/administration/reports" className="block rounded-3xl border border-cyan-200 bg-cyan-50 p-5 shadow-sm hover:bg-cyan-100"><p className="font-semibold text-slate-950">Review Monthly Reports</p><p className="mt-1 text-sm text-slate-600">Open reports awaiting Administration approval, correction, or rejection.</p></Link><section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-4"><div><h2 className="text-lg font-semibold text-slate-950">Recent Reviews</h2><p className="mt-1 text-sm text-slate-500">Latest Administration decisions recorded in the system.</p></div></div><div className="mt-5 overflow-x-auto"><table className="min-w-full divide-y divide-slate-200"><thead className="bg-slate-50"><tr>{["Location", "Month", "Decision", "Reviewer", "Date"].map((heading) => <th key={heading} className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">{heading}</th>)}</tr></thead><tbody className="divide-y divide-slate-200">{data.recentReviews.length === 0 ? <tr><td colSpan={5} className="px-4 py-10 text-center text-sm text-slate-500">No recent reviews.</td></tr> : data.recentReviews.map((review) => <tr key={review.id}><td className="px-4 py-4 text-sm font-medium text-slate-900">{review.report.location.name}</td><td className="px-4 py-4 text-sm text-slate-600">{reportMonth(review.report.month, review.report.year)}</td><td className="px-4 py-4 text-sm font-semibold text-slate-700">{review.decision}</td><td className="px-4 py-4 text-sm text-slate-600">{review.reviewer.name}</td><td className="px-4 py-4 text-sm text-slate-600">{formatDate(review.createdAt)}</td></tr>)}</tbody></table></div></section></div></AppShell>;
}
function Stat({ title, value }: { title: string; value: number }) { return <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm font-medium text-slate-500">{title}</p><p className="mt-2 text-3xl font-semibold text-slate-950">{value}</p></article>; }
function AccessDenied() { return <main className="flex min-h-screen items-center justify-center bg-slate-50 p-6"><div className="rounded-3xl border border-red-200 bg-red-50 p-8"><h1 className="text-2xl font-semibold text-red-950">Access Denied</h1><p className="mt-2 text-sm text-red-800">You do not have permission to access this dashboard.</p><Link href="/dashboard" className="mt-5 inline-flex rounded-2xl bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">Return to Dashboard</Link></div></main>; }
function ErrorState() { return <div className="rounded-3xl border border-red-200 bg-red-50 p-8"><h1 className="text-2xl font-semibold text-red-950">Unable to load dashboard data.</h1><p className="mt-2 text-sm text-red-800">Please try again.</p></div>; }
