ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'LOCATION_TASK_CREATED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'LOCATION_TASK_UPDATED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'LOCATION_TASK_ACTIVATED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'LOCATION_TASK_DEACTIVATED';
