import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { AppShell } from "@/app/_components/app-shell";
import { PrintReportButton } from "@/app/monthly-reports/[id]/print-report-button";
import { getAuthContext } from "@/lib/auth";
import { getAdministrationReviewHistory } from "@/lib/administration-review";
import { getMonthlyReport } from "@/lib/monthly-reports";
import { prisma } from "@/lib/prisma";
import { ReviewActions } from "./review-actions";

const dateLabel = (year: number, month: number) => new Intl.DateTimeFormat("en", { month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(Date.UTC(year, month - 1, 1)));
const formatDate = (date: Date | null) => date ? new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "long", year: "numeric" }).format(date) : "-";
const money = (value: unknown) => value == null ? "-" : Number(value).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const resultLabel = (result: string) => result === "P" ? "Passed" : result === "X" ? "Failed" : "Not Applicable";
const statusLabel = (status: string) => status === "CORRECTION_REQUESTED" ? "CORRECTION REQUIRED" : status === "ADMIN_APPROVED" ? "APPROVED" : status === "ADMIN_REJECTED" ? "REJECTED" : status;

export default async function AdministrationReportPage({ params }: { params: Promise<{ id: string }> }) {
  const { sessionUser, appUser } = await getAuthContext();
  if (!sessionUser) redirect("/login");
  if (!appUser || appUser.role !== "ADMINISTRATION_OFFICER") return <main className="p-8">You do not have permission to review reports.</main>;
  const id = (await params).id;
  const [data, history] = await Promise.all([getMonthlyReport(prisma, { userId: appUser.id, role: appUser.role }, id), getAdministrationReviewHistory(prisma, appUser, id)]);
  if (!data) notFound();
  const { report, evaluations, attendance } = data;
  const canReview = report.status === "SUBMITTED" || report.status === "RESUBMITTED";
  const missingTasks = report.taskSummaries.reduce((total, task) => total + task.missingOccurrences, 0);
  return <AppShell user={appUser}><div className="mx-auto flex w-full max-w-7xl flex-col gap-6 print-report"><div className="flex flex-wrap justify-between gap-3 print:hidden"><Link href="/administration/reports" className="text-sm font-semibold text-cyan-700">&larr; Back to Monthly Reports</Link><PrintReportButton /></div>
    <header className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><p className="text-xs font-semibold uppercase tracking-[0.3em] text-cyan-700">Administration Review</p><div className="mt-5 flex flex-wrap items-end justify-between gap-5"><div><h1 className="text-3xl font-semibold text-slate-950">Monthly Report</h1><p className="mt-2 text-lg text-slate-600">{report.location.name} · {dateLabel(report.year, report.month)}</p></div><span className="rounded-full bg-slate-100 px-3 py-1.5 text-sm font-semibold text-slate-700">{statusLabel(report.status)}</span></div><dl className="mt-8 grid gap-5 border-t border-slate-100 pt-6 sm:grid-cols-2 lg:grid-cols-5"><Meta label="Location" value={`${report.location.name} (${report.location.code})`} /><Meta label="Generated" value={formatDate(report.generatedAt)} /><Meta label="Submitted" value={formatDate(report.submittedAt)} /><Meta label="Report ID" value={report.id} /><Meta label="Task Evaluations" value={String(evaluations.length)} /></dl></header>
    <Section title="Report Completeness"><div className="grid gap-3 sm:grid-cols-3"><Completeness label="Cleaning Evaluations" complete={missingTasks === 0} detail={missingTasks ? `${missingTasks} missing expected evaluation(s)` : "All expected evaluations present"} /><Completeness label="PHI Daily Records" complete={report.isComplete && !report.processingError} detail={report.processingError ?? `${attendance.length} record(s) captured`} /><Completeness label="Monthly Task Summaries" complete={report.taskSummaries.length > 0} detail={`${report.taskSummaries.length} task(s)`} /></div>{report.processingError ? <p className="mt-4 rounded-2xl bg-amber-50 p-4 text-sm text-amber-900">{report.processingError}</p> : null}</Section>
    {canReview ? <ReviewActions reportId={report.id} /> : <div className="rounded-3xl border border-slate-200 bg-white p-5 text-sm text-slate-700 shadow-sm">Review actions are locked for status <span className="font-semibold">{statusLabel(report.status)}</span>.</div>}
    <Section title="Cleaning Task Summary"><Table><thead><tr>{["Task", "Category", "Frequency", "P", "X", "NA", "Applicable", "Completion %", "Allocated Amount", "Remarks"].map((heading) => <th key={heading} className="th">{heading}</th>)}</tr></thead><tbody>{report.taskSummaries.map((task) => <tr key={task.id}><td className="td font-medium text-slate-900">{task.taskNameSnapshot}</td><td className="td">{task.categorySnapshot}</td><td className="td">{task.frequencySnapshot}</td><td className="td">{task.passedOccurrences}</td><td className="td">{task.failedOccurrences}</td><td className="td">{task.notApplicableOccurrences}</td><td className="td">{task.applicableOccurrences}</td><td className="td font-semibold">{String(task.completionPercentage)}%</td><td className="td">{money(task.allocatedAmount)}</td><td className="td">{task.taskRemarks ? "Recorded" : "-"}</td></tr>)}</tbody></Table></Section>
    <Section title="Daily Evaluation History"><Table><thead><tr>{["Date", "Task", "Result", "Evaluating Officer", "Remark"].map((heading) => <th key={heading} className="th">{heading}</th>)}</tr></thead><tbody>{evaluations.length === 0 ? <Empty colSpan={5} /> : evaluations.map((evaluation) => <tr key={evaluation.id}><td className="td">{evaluation.evaluationDate}</td><td className="td text-slate-900">{evaluation.locationTask.task.name}</td><td className="td"><span className="font-semibold">{evaluation.result}</span> <span className="text-slate-500">{resultLabel(evaluation.result)}</span></td><td className="td">{evaluation.evaluatingOfficer.name}</td><td className="td">{evaluation.remark ?? "-"}</td></tr>)}</tbody></Table></Section>
    <Section title="PHI Daily Total-Present History"><Table><thead><tr>{["Date", "Total Present", "PHI", "Remarks"].map((heading) => <th key={heading} className="th">{heading}</th>)}</tr></thead><tbody>{attendance.length === 0 ? <Empty colSpan={4} /> : attendance.map((entry) => <tr key={entry.id}><td className="td">{entry.attendanceDate}</td><td className="td font-semibold text-slate-900">{entry.totalPresentCount}</td><td className="td">PHI record</td><td className="td">{entry.remark ?? "-"}</td></tr>)}</tbody></Table></Section>
    <Section title="Review History"><div className="space-y-4">{history.length === 0 ? <p className="text-sm text-slate-500">No Administration review history.</p> : history.map((review) => <article key={review.id} className="border-l-2 border-cyan-600 pl-4"><div className="flex flex-wrap justify-between gap-2"><p className="font-semibold text-slate-900">{review.decision}</p><time className="text-sm text-slate-500">{formatDate(review.reviewedAt)}</time></div><p className="mt-1 text-sm text-slate-600">Reviewed by {review.reviewer.name}</p><p className="mt-2 text-sm text-slate-700">{review.remarks ?? "No remarks recorded."}</p></article>)}</div></Section>
  </div></AppShell>;
}
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 className="mb-5 text-lg font-semibold text-slate-950">{title}</h2>{children}</section>; }
function Table({ children }: { children: React.ReactNode }) { return <div className="overflow-x-auto"><table className="min-w-full divide-y divide-slate-200">{children}</table></div>; }
function Empty({ colSpan }: { colSpan: number }) { return <tr><td colSpan={colSpan} className="px-4 py-8 text-center text-sm text-slate-500">No records available.</td></tr>; }
function Meta({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 truncate text-sm text-slate-700">{value}</dd></div>; }
function Completeness({ label, complete, detail }: { label: string; complete: boolean; detail: string }) { return <div className={`rounded-2xl border p-4 ${complete ? "border-emerald-200 bg-emerald-50" : "border-amber-200 bg-amber-50"}`}><p className="font-semibold text-slate-900">{complete ? "Complete" : "Incomplete"}</p><p className="mt-1 text-sm text-slate-700">{label}</p><p className="mt-1 text-xs text-slate-600">{detail}</p></div>; }
