"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";

type Decision = "approve" | "request-correction" | "reject";
export function ReviewActions({ reportId }: { reportId: string }) {
  const router = useRouter(); const [decision, setDecision] = useState<Decision | null>(null); const [remarks, setRemarks] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  async function submit() { if (!decision) return; setBusy(true); setError(null); const response = await fetch(`/api/admin/monthly-reports/${reportId}/${decision}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ remarks }) }); const body = await response.json().catch(() => ({})); setBusy(false); if (!response.ok) { setError(body.error ?? "Unable to complete this review. Please refresh and try again."); return; } router.refresh(); setDecision(null); setRemarks(""); }
  return <div className="rounded-3xl border border-cyan-200 bg-cyan-50 p-5"><h2 className="text-lg font-semibold text-slate-950">Administration decision</h2><p className="mt-1 text-sm text-slate-600">Choose one decision. Approval remarks are optional; correction and rejection remarks are required.</p><div className="mt-4 flex flex-wrap gap-3"><button onClick={() => setDecision("approve")} className="rounded-2xl bg-emerald-700 px-4 py-2.5 text-sm font-semibold text-white">Approve</button><button onClick={() => setDecision("request-correction")} className="rounded-2xl bg-amber-600 px-4 py-2.5 text-sm font-semibold text-white">Request Correction</button><button onClick={() => setDecision("reject")} className="rounded-2xl bg-red-700 px-4 py-2.5 text-sm font-semibold text-white">Reject</button></div>{decision ? <div className="mt-5 rounded-2xl border border-slate-200 bg-white p-4"><label className="block text-sm font-semibold text-slate-800">{decision === "approve" ? "Approval remarks (optional)" : decision === "reject" ? "Rejection remarks (required)" : "Correction remarks (required)"}<textarea value={remarks} onChange={(event) => setRemarks(event.target.value)} rows={4} className="mt-2 w-full rounded-2xl border border-slate-300 p-3 text-sm outline-none focus:border-slate-900" /></label>{error ? <p className="mt-3 text-sm text-red-700" role="alert">{error}</p> : null}<div className="mt-4 flex gap-3"><button disabled={busy} onClick={submit} className="rounded-2xl bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{busy ? "Submitting..." : "Confirm decision"}</button><button disabled={busy} onClick={() => setDecision(null)} className="rounded-2xl border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700">Cancel</button></div></div> : null}</div>;
}
