ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'LOCATION_CREATED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'LOCATION_UPDATED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'LOCATION_ACTIVATED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'LOCATION_DEACTIVATED';
