import Link from "next/link";
import { redirect } from "next/navigation";
import { AppShell } from "@/app/_components/app-shell";
import { getAuthContext } from "@/lib/auth";
import { getAdministrationReferenceLocations, getAdministrationSummary, listAdministrationReports } from "@/lib/administration-review";
import { prisma } from "@/lib/prisma";

type SearchParams = Promise<Record<string, string | string[] | undefined>>;
const valueOf = (value: string | string[] | undefined) => Array.isArray(value) ? value[0] : value;
const dateLabel = (year: number, month: number) => new Intl.DateTimeFormat("en", { month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(Date.UTC(year, month - 1, 1)));
const formatDate = (date: Date | null) => date ? new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric" }).format(date) : "-";
const statusLabel = (status: string) => status === "CORRECTION_REQUESTED" ? "CORRECTION REQUIRED" : status === "ADMIN_APPROVED" ? "APPROVED" : status === "ADMIN_REJECTED" ? "REJECTED" : status;

export default async function AdministrationReportsPage({ searchParams }: { searchParams: SearchParams }) {
  const { sessionUser, appUser } = await getAuthContext();
  if (!sessionUser) redirect("/login");
  if (!appUser || appUser.role !== "ADMINISTRATION_OFFICER") return <main className="p-8">You do not have permission to view Administration reviews.</main>;
  const params = await searchParams;
  const number = (key: string) => Number(valueOf(params[key])) || undefined;
  const filters = { query: valueOf(params.query), month: number("month"), year: number("year"), locationId: valueOf(params.locationId), status: valueOf(params.status), page: number("page") };
  const [data, locations, summary] = await Promise.all([listAdministrationReports(prisma, appUser, filters), getAdministrationReferenceLocations(prisma, appUser), getAdministrationSummary(prisma, appUser)]);
  const years = Array.from(new Set(data.reports.map((report) => report.year))).sort((a, b) => b - a);
    return <AppShell user={appUser}><div className="mx-auto flex w-full max-w-7xl flex-col gap-6">
      <header><p className="text-sm font-semibold uppercase tracking-[0.3em] text-cyan-700">Administration</p><h1 className="mt-2 text-3xl font-semibold text-slate-950">Monthly Report Review</h1><p className="mt-2 text-sm text-slate-600">Review submitted monthly cleaning service reports without changing daily records.</p></header>
      <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><Summary label="Pending Review" value={summary.pending} /><Summary label="Approved" value={summary.approved} /><Summary label="Correction Required" value={summary.correction} /><Summary label="Rejected" value={summary.rejected} /><Summary label="Submitted" value={summary.submitted} /></section>
      <form method="get" className="grid gap-3 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:grid-cols-2 lg:grid-cols-5"><Field label="Search"><input name="query" defaultValue={valueOf(params.query)} placeholder="Search location..." className="control" /></Field><Field label="Month"><select name="month" defaultValue={number("month") ?? ""} className="control"><option value="">All months</option>{Array.from({ length: 12 }, (_, i) => <option key={i + 1} value={i + 1}>{new Intl.DateTimeFormat("en", { month: "long" }).format(new Date(Date.UTC(2020, i, 1)))}</option>)}</select></Field><Field label="Year"><select name="year" defaultValue={number("year") ?? ""} className="control"><option value="">All years</option>{years.map((year) => <option key={year} value={year}>{year}</option>)}</select></Field><Field label="Location"><select name="locationId" defaultValue={valueOf(params.locationId) ?? ""} className="control"><option value="">All locations</option>{locations.map((location) => <option key={location.id} value={location.id}>{location.code} - {location.name}</option>)}</select></Field><Field label="Status"><select name="status" defaultValue={valueOf(params.status) ?? ""} className="control"><option value="">All statuses</option>{["SUBMITTED", "RESUBMITTED", "CORRECTION_REQUESTED", "ADMIN_APPROVED", "ADMIN_REJECTED"].map((status) => <option key={status} value={status}>{statusLabel(status)}</option>)}</select></Field><div className="flex items-end sm:col-span-2 lg:col-span-5"><button type="submit" className="rounded-2xl bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">Apply filters</button></div></form>
      <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-full divide-y divide-slate-200"><thead className="bg-slate-50"><tr>{["Reporting Month", "Location", "Status", "Generated", "Submitted", "Reviewed", "Reviewer", "Action"].map((heading) => <th key={heading} className="px-5 py-3 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">{heading}</th>)}</tr></thead><tbody className="divide-y divide-slate-200">{data.reports.length === 0 ? <tr><td colSpan={8} className="px-5 py-16 text-center"><p className="font-semibold text-slate-900">No monthly reports match these filters.</p></td></tr> : data.reports.map((report) => { const latest = report.administrationReviews[0]; const reviewable = report.status === "SUBMITTED" || report.status === "RESUBMITTED"; return <tr key={report.id} className="hover:bg-slate-50"><td className="whitespace-nowrap px-5 py-4 text-sm font-medium text-slate-900">{dateLabel(report.year, report.month)}</td><td className="px-5 py-4 text-sm text-slate-700"><span className="font-medium">{report.location.code}</span><span className="block text-slate-500">{report.location.name}</span></td><td className="px-5 py-4"><span className="inline-flex rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-700">{statusLabel(report.status)}</span></td><td className="whitespace-nowrap px-5 py-4 text-sm text-slate-600">{formatDate(report.generatedAt)}</td><td className="whitespace-nowrap px-5 py-4 text-sm text-slate-600">{formatDate(report.submittedAt)}</td><td className="whitespace-nowrap px-5 py-4 text-sm text-slate-600">{formatDate(latest?.reviewedAt ?? null)}</td><td className="px-5 py-4 text-sm text-slate-600">{latest?.reviewer.name ?? "-"}</td><td className="px-5 py-4"><Link href={`/administration/reports/${report.id}`} className="font-semibold text-cyan-700 hover:text-cyan-900">{reviewable ? "Review" : "View"}</Link></td></tr>; })}</tbody></table></div>{data.totalPages > 1 ? <div className="flex justify-between border-t border-slate-200 px-5 py-4 text-sm"><span className="text-slate-500">Page {data.page} of {data.totalPages}</span><div className="flex gap-2">{data.page > 1 ? <Link className="rounded-xl border px-3 py-2" href={{ query: { ...Object.fromEntries(Object.entries(params).map(([key, value]) => [key, valueOf(value) ?? ""])), page: String(data.page - 1) } }}>Previous</Link> : null}{data.page < data.totalPages ? <Link className="rounded-xl border px-3 py-2" href={{ query: { ...Object.fromEntries(Object.entries(params).map(([key, value]) => [key, valueOf(value) ?? ""])), page: String(data.page + 1) } }}>Next</Link> : null}</div></div> : null}</section>
    </div></AppShell>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label><span className="mb-1.5 block text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</span>{children}</label>; }
function Summary({ label, value }: { label: string; value: number }) { return <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold text-slate-950">{value}</p></div>; }
