ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'CLEANING_TASK_CREATED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'CLEANING_TASK_UPDATED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'CLEANING_TASK_ACTIVATED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'CLEANING_TASK_DEACTIVATED';
